services:
  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on: [db]
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config/odoo-docker.conf:/etc/odoo/odoo.conf:ro        # 你的配置在 config/
      - ./odoo:/usr/lib/python3/dist-packages/odoo       # 用本地 Odoo 源码覆盖容器内 odoo 包
      - ./addons:/mnt/odoo-addons                        # 本地官方/社区 addons
      - ./custom-addons:/mnt/custom-addons               # 你的客制化模块
    environment:
      - HOST=db
      - PORT=5432              # ← 新增
      - USER=odoo
      - PASSWORD=odoo
    command: ["odoo", "-c", "/etc/odoo/odoo.conf", "--dev=reload,xml,qweb,assets"]
    restart: always

  db:
    image: postgres:16
    container_name: pg
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-data:
  db-data:
