[options]
addons_path = ./addons
db_name = odoo_cn
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo
logfile = odoo.log
dev = all
admin_passwd = $pbkdf2-sha512$600000$mZMyRkhJCaHUOsc4J6T0fg$LtzPg91bIStY47H.i5j/KVp0IXUnIogZ3g5yfDxn/HXmDW5gtSnOqj/NrfE4IQlPhZlXkLwFI2cge1O8TjVHWg

