services:
  odoo:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: odoo-18
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ../odoo:/usr/lib/python3/dist-packages/odoo
      - ../addons:/mnt/odoo-addons
      - ../custom-addons:/mnt/custom-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - odoo-data:/var/lib/odoo
      - /var/log/odoo:/var/log/odoo
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
      POSTGRES_DB: postgres
      AWS_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      AWS_DEFAULT_REGION: ${MINIO_REGION_NAME}
      AWS_ENDPOINT_URL_S3: http://minio:${MINIO_API_PORT}
    command: >
      sh -c "sleep 5 && 
      odoo -c /etc/odoo/odoo.conf --init=component,storage_backend,storage_backend_s3,fs_storage,fs_attachment,partner_level --without-demo=all --stop-after-init &&
      odoo -c /etc/odoo/odoo.conf"
    restart: unless-stopped
    networks:
      - odoo-network

  db:
    image: postgres:16
    container_name: odoo-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5433"  # 可选：用于调试数据库连接
    restart: unless-stopped
    networks:
      - odoo-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION_NAME: ${MINIO_REGION_NAME}
    volumes:
      - ${MINIO_DATA_DIR}:/data
    ports: ["${MINIO_API_PORT}:9000","${MINIO_CONSOLE_PORT}:9001"]
    networks: [odoo-network]
volumes:
  odoo-data:
  db-data:

networks:
  odoo-network:
    driver: bridge
