[options]
addons_path = /mnt/custom-addons,/mnt/odoo-addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = postgres
list_db = True
longpolling_port = 8072
logfile = /var/log/odoo/odoo.log
log_level = info
dev = reload,xml,qweb,assets
limit_time_cpu = 0
limit_time_real = 0
workers = 0
admin_passwd = $pbkdf2-sha512$600000$mZMyRkhJCaHUOsc4J6T0fg$LtzPg91bIStY47H.i5j/KVp0IXUnIogZ3g5yfDxn/HXmDW5gtSnOqj/NrfE4IQlPhZlXkLwFI2cge1O8TjVHWg
data_dir = /var/lib/odoo