[options]
; addons_path = addons, custom-addons, odoo/addons
addons_path = /Users/tju/Workspace/Projects/ongoing/odoo/addons, /Users/tju/Workspace/Projects/ongoing/odoo/custom-addons, /Users/tju/Workspace/Projects/ongoing/odoo/odoo/addons
db_name = odoo_cn
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = odoo
logfile = odoo.log
; 热加载
dev = all

; 取消 CPU/Real 限制
limit_time_cpu = 0
limit_time_real = 0

; 单进程模式（开发环境一般这么开）
workers = 0
admin_passwd = $pbkdf2-sha512$600000$mZMyRkhJCaHUOsc4J6T0fg$LtzPg91bIStY47H.i5j/KVp0IXUnIogZ3g5yfDxn/HXmDW5gtSnOqj/NrfE4IQlPhZlXkLwFI2cge1O8TjVHWg